Develop
BigBiba/sultan-shop pull request #13
Opened 2024-11-19 15:52 UTC by BigBiba

2024-11-21 11:30 UTC, olya-yevsieienko requested changes
Молодцы. Очень круто, что подключили Toolkit  и ТS.
Нужно поправить несколько моментов:
1. Форматирование проверить во всех файлах. Должны быть одинаковцые отступы и пустые строки между блоками кода.
2. Порядок подключения импортов.
3. Порядок написания css свойств.

2024-11-21 11:30 UTC, olya-yevsieienko commented on .vscode/extensions.json
> +}
В конце каждого файла должна быть одна пустая строка.
https://dev.to/documendous/why-you-should-end-your-source-files-with-a-new-line-156g

Проверить во всех файлах.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/app/StoreProvider.tsx
> +import { setLanguage } from '../redux/languageSlice'
```suggestion
'use client';

import { useRef } from 'react';
import { Provider } from 'react-redux';
import { makeStore, AppStore } from '../redux/store';
import { setLanguage } from '../redux/languageSlice';

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/app/StoreProvider.tsx
> +  }
```suggestion
  const storeRef = useRef<AppStore>();
  
  if (!storeRef.current) {
    storeRef.current = makeStore();
    storeRef.current.dispatch(setLanguage(lang));
  }

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/app/getLang.ts
> +}
Проверить во всех файлаз наличие точки с запятой или запятой в конце строки.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/app/getLang.ts
> +  return lang as string || 'ru'; // 'en' — значение по умолчанию
ru вынести в константу.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/app/globals.scss
> +
Форматирование.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/app/i18n.js
> +  });
Удалить все лишние комментарии.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/app/layout.tsx
> + </LanguageProvider>
Форматирование.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/app/page.tsx
> +import Slider from "@/components/Slider/slider"
Добавить в файл компонентов файл компонентов файл index.ts, чтобы импорты выглядели более понятными.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/AddressInfo/AddressInfo.module.scss
> +        color: #3F4E65;
Все цвета должны бытьв переменных.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/AddressInfo/AddressInfo.module.scss
> +    height: 39px;
```suggestion
    height: 40px;

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/AddressInfo/AddressInfo.tsx
> +  }
Проверить форматирование. Одна пустая строка между логическими и функциональными блоками кода, пунктуация.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/AddressInfo/AddressInfo.tsx
> +    // const { t } = await useTranslation(lang)
Если не испольузется, то нужно убрать.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +        transform: scale(-1, 1);
```suggestion
    position: relative;
    
    .image {
        transform: scale(-1, 1);

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +        width: 921px;
```suggestion
        width: 920px;

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +                color: #FFFFFF;
Все цвета в переменные.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +                margin-top: 91px;
```suggestion
                margin-top: 92px;

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +        <div className={styles.container}>
```suggestion
        <section className={styles.container}>

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +                    <p className={styles.text2}>оптом по кокчетаву и области</p>
Непонятные названия классов, лучше подобрать другие.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +                    <p className={styles.text1}>Бытовая химия, косметика и хозтовары</p>
```suggestion
                    <h1 className={styles.text1}>Бытовая химия, косметика и хозтовары</p>

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +                    <Button text="В КАТАЛОГ" icon_src="" icon_alt="" width={300} height={95}></Button>
```suggestion
                    <Button
                      text="В КАТАЛОГ"
                      iconSrc=""
                      iconAlt=""
                      width={300}
                      height={95}
                    />

```
Если атрибутов больше двух, то переносить их на новую строчку. 
Атрибуты принято пистать таким образом iconSrc.
Не нужно передавать пустую строку. Если нужно, то можно задать пропсам в компоненте значения по умолчанию.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +                        <div className={styles.plus2}>Бесплатная доставка<br /> по <span>Кокчетаву от 10 тыс ₸</span></div>
```suggestion
                        <div className={styles.plus2}>
                          Бесплатная доставка<br />
                          по <span>Кокчетаву от 10 тыс ₸</span>
                        </div>

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +                        <div className={styles.plus2}>Бесплатная доставка<br /> по <span>Кокчетаву от 10 тыс ₸</span></div>
Это одинаковые элементы, зачем им разные классы?

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +
Лишняя пустая строка.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Basket/Basket.tsx
> +import * as m from "@/paraglide/messages.js"
Порядок подключения импортов.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Basket/Basket.tsx
> +                <Image className={styles.logo} src={BasketLogo} alt=""></Image>
```suggestion
                <Image
                  className={styles.logo}
                  src={BasketLogo}
                  alt=""
                />

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.tsx
> +import doc from './doc.png';
Порядок подключения импортов.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.tsx
> +          <div className="iconText" style={{ flex: 1, marginRight: '24px', display: 'flex', alignItems: 'center' }}>
Все стили передает с помощью классов, не инлайново.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Contacts/image_1.png
Зачем две картинки?)

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Footer/footer.tsx
> +                </ul>
Использовать рендер списков. 
А ещё это навигация, нужен определенный тег.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Footer/footer.tsx
> +                </ul>
Рендер списков.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Footer/footer.tsx
> +                <Button text='Прайс-лист' icon_src={DownloadLogo} icon_alt='' width={214} height={59}></Button>
О кнопке уже писала. Нужно проверить везде.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Footer/footer.tsx
> +                <p className="call-request header-text">Заказать звонок</p>
Это должна быть ссылка для звонка.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Header/Header.module.scss
> +        width: 1920;
```suggestion
    display: flex;
    flex-direction: column;
    
    .top {
        width: 1920px;
        
        .info_container {
            display: flex;
        }
```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Header/Header.module.scss
> +        // }
Если не нужен, лучше удалить.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Header/Header.tsx
> +    return (
```suggestion
import * as m from "@/paraglide/messages.js"

export default function Header({lang}: { lang: string}) {
    return (

```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Items/promItems.js
> +      <strong><h2 style={{ textAlign: 'left', fontSize: '30px' }}><span style={{ color: '#FFBF00' }}>Акционные</span> товары</h2></strong>
А зачем в strong положили h2?

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Items/promItems.js
> +            </div>
```suggestion
            <p className="item-details">
              <strong className="item-barcode">Штрихкод:</strong>
              {item.barcode}
            </p>
```
лучше так реализовать подобный контент.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Items/promItems.js
> +            </footer>
Форматирование.
А почему тут футер?)

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Items/promItems.js
> +            </div>
Лучше убрать лишние комментарии.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/MainLogo/MainLogo.tsx
> +}
Это можно не выносить в отбедьный компонент.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/PhoneInfo/PhoneInfo.module.scss
> +            background-color: #1FD85D; // Зеленый цвет для индикатора
Вот лучше вынести его в переменную с понятным именем)

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Product categories/categories.js
Название папки должно быть одним словом, где каждое отдельное слово пишется с большой буквы.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Product categories/categories.js
> +      <strong><h2 style={{ textAlign: 'left', fontSize: '30px' }}><span style={{ color: '#FFBF00' }}>Категории</span> товаров</h2></strong>
Кажется, это такой же компонент как и  популярные товары. Лучше не дублировать код.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/RefsList/RefsList.module.scss
> +}
```suggestion
    }
}
```

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Slider/slider.jsx
> +    }, []);
А почему нельзя сразу инициализировать свайпер?

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Slider/slider.jsx
> +
Порядок подключения импортов.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Slider/slider.jsx
> +                            <Button text='Принять участие' text_size={16} icon_src={''} icon_alt='' width={200} height={45}></Button>
Форматирование.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/Sponsor/sponsor.tsx
> +            </strong>
Не нужно класть загoловок в strong.

2024-11-21 11:30 UTC, olya-yevsieienko commented on src/components/shared/Button.tsx
> +    return (
```suggestion
}

export function Button({text, text_size, icon_src, icon_alt, width, height}: ButtonInterface) {
    return (

```

2024-12-04 16:21 UTC, BigBiba commented on src/app/page.tsx
> +import Slider from "@/components/Slider/slider"
так удобнее

2024-12-07 10:37 UTC, olya-yevsieienko requested changes

2024-12-07 10:37 UTC, olya-yevsieienko commented on messages/en.json
> +}
Пустая строка в конце каждого файла. Проверьте, пожалуйста, везде.

2024-12-07 10:37 UTC, olya-yevsieienko commented on project.inlang/.gitignore
> +cache
Наверное, это не должно попадать в гит.

2024-12-07 10:37 UTC, olya-yevsieienko commented on project.inlang/project_id
> +49320a15d42e1ec12762ceaa156e15f4eeeeba82820adbcc5319fa15b6e4e0db
Наверное, это не должно попадать в гит.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/StoreProvider.tsx
> +  children: React.ReactNode
Следует соблюдать форматирование.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/StoreProvider.tsx
> +
```suggestion
'use client';

import { useRef } from 'react';
import { Provider } from 'react-redux';
import { makeStore, AppStore } from '../redux/store';
import { setLanguage } from '../redux/languageSlice';

```
Возможно, это кажется незначительной деталью. Но следует соблюдать правила написания кода всегда и обращать на это внимание.
Порядок в написании кода упрощает работу вам и вашим коллегам.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/StoreProvider.tsx
> +}
```suggestion
    storeRef.current.dispatch(setLanguage(lang));
  }

  return <Provider store={storeRef.current}>{children}</Provider>
}

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/globals.scss
> +:root { font-family: "Inter", sans-serif; }
```suggestion
:root {
    font-family: "Inter", sans-serif;
}

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/globals.scss
> +    font-style: italic;
Во всех файлах нужно выбрать одинаковые отступы: либо два, либо четыре пробела. Чаще на проектах четыре.
Проверить во всех файлах.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/layout.tsx
> +import "./globals.scss";
```suggestion
import { LanguageProvider } from "@inlang/paraglide-next";
import { languageTag } from "@/paraglide/runtime.js";
import { dir } from 'i18next';
import "./globals.scss";
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/page.tsx
> +import Sponsor from "@/components/Sponsor/sponsor"
```suggestion
import PromItems from "@/components/Items/promItems";
import Categories from "@/components/Product categories/categories";
import { Footer } from "@/components/Footer/footer";
import Slider from "@/components/Slider/slider";
import Sponsor from "@/components/Sponsor/sponsor";
import styles from "./page.module.scss";
```
Стили подключаются в самом конце.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/page.tsx
> +      <Header lang={lang}></Header>
```suggestion
      <Header lang={lang}  />
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/app/vars.scss
> +$search-bar-background-color: #eeeeee;
Либо верхний регистр, либо нижний для переменных.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/AddressInfo/AddressInfo.tsx
> +
```suggestion
import Image from "next/image";
import PinLogo from "@/public/icons/pin.svg";
import * as m from "@/paraglide/messages.js";

import styles from "./AddressInfo.module.scss";


```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/AddressInfo/AddressInfo.tsx
> +    )
```suggestion
    return (
        <div className={styles.info}>
           <Image className={styles.logo} src={PinLogo} alt="Pin />
            <p>
                <span>{m.main_header_address_main()}</span><br/>
                {m.main_header_address_sub()}
            </p>
        </div>
    )

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +        max-height: 100%;
```suggestion
        transform: scale(-1, 1);
        object-fit: cover;
        max-height: 100%;

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +                width: 570px;
```suggestion
        .all_text {
            margin-left: 277px;
            
            .text_products {
                width: 570px;

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +                span.plus {
```suggestion
                .plus {

```
Лучше не повышать специфичность селекторов без надобности.
https://doka.guide/css/specificity/

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +                }
Здесь дублируются стили. Можно найти более универсальное решение.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.module.scss
> +
```suggestion

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +
```suggestion
import Image from "next/image";
import BannerImage from "@/public/images/banner.png";
import { Button } from "../shared/Button";

import styles from "./Banner.module.scss";


```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +            <Image className={styles.image} src={BannerImage} alt=""></Image>
```suggestion
            <Image className={styles.image} src={BannerImage} alt="" />

```
У каждого изображения должен быть alt.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +                    <Button text="В КАТАЛОГ"
Переводы.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +                    <div className={styles.pluses_container}>
Форматирование.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Banner/Banner.tsx
> +
Это не было исправлено.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Basket/Basket.module.scss
> +            color: vars.$black;
```suggestion
        }
        
        .sum {
            color: vars.$black;

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Basket/Basket.module.scss
> +}
```suggestion
        }
    }
}

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Basket/Basket.tsx
> +    return (
```suggestion
export default function Basket() {
    const cartTotal = 0;
    const cartCount = 3;
    
    return (

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Basket/Basket.tsx
> +                <Image className={styles.logo} src={BasketLogo} alt=""></Image>
И это не было исправлено.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.scss
> +@media (max-width: 1280px) {
Все значения для media должны браться из переменных.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.scss
> +@media (max-width: 1024px) {
Все значения для media должны браться из переменных. Проверить везде.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.scss
> +    color: #3F4E65;
Все цвета должны выноситься в переменные.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.tsx
> +          <div className="iconText" style={{ flex: 1, marginRight: '24px', display: 'flex', alignItems: 'center' }}>
Зачем вы отмечаете как выполненное то, что не было исправлено?

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.tsx
> +            <p style={{ fontWeight: 400, fontSize: '14px', lineHeight: '18.2px', color: 'var(--blue)' }}>
Все стили передает с помощью классов, не инлайново.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.tsx
> +            <h3 style={{ marginBottom: '8px' }}>Отдел продаж:</h3>
Все стили передает с помощью классов, не инлайново.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.tsx
> +          <div className="sale" style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
Все стили передает с помощью классов, не инлайново.
Здесь даже класс указан.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Contacts/contacts.tsx
> +        <div className="iconText" style={{ marginTop: '40px', display: 'flex', alignItems: 'center' }}>
Все стили передает с помощью классов, не инлайново.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Footer/Footer.scss
> +    background-color: #F39C12;
Все цвета должны быть в переменных.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Footer/Footer.scss
> +        background-color: #E67E22;
Все цвета должны быть в переменных.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Footer/Footer.scss
> +    color: #333;
Все цвета должны быть в переменных.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Footer/Footer.scss
> +    font-family: 'Arial', sans-serif;
font-family: 'Arial', sans-serif;
Зачем это дублируется везде? Возможно, лучшим решением будет добавить этот стиль общему родителю.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Footer/footer.tsx
> +                </ul>
Не исправлено.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Footer/footer.tsx
> +                </ul>
Не исправлено.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Header/Header.module.scss
> +        width: 1920;
Не исправлено.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Header/Header.tsx
> +import MailInfo from "../MailInfo/MailInfo"
```suggestion
import MailInfo from "../MailInfo/MailInfo";

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Header/Header.tsx
> +import styles from "./Header.module.scss"
```suggestion
import styles from "./Header.module.scss";

```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Header/Header.tsx
> +                    <MailInfo></MailInfo>
```suggestion
                    <AddressInfo lang={lang} />
                    <MailInfo />
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Header/Header.tsx
> +                <MainLogo></MainLogo>
```suggestion
                <RefsList />
            </div>
            <hr />
            <div className={styles.bottom}>
                <MainLogo />
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Header/Header.tsx
> +            </div>
Нужно проверить форматирование.
Если в у какого-то тега или компонента нет вложенного контента, можно закрывать тег в том же, где и открывается.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Header/Header.tsx
> +    )
```suggestion
    );
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Items/data.js
> +import image4 from './4.jpg'
```suggestion
import image1 from './1.jpg';
import image2 from './2.jpg';
import image3 from './3.jpg';
import image4 from './4.jpg';
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Items/data.js
> +}, {
```suggestion
  id: 0, // Used in JSX as a key
  ml: '450',
  imageId: image1,
  name: 'SORTI Средство для мытья посуды',
  barcode: '40215987352',
  manufacturer: 'Нефис',
  brand: 'AOS',
  price: '48,78',
},
{
  id: 1, // Used in JSX as a key
  ml: '450',
  imageId: image2,
  name: 'AOS Средство для мытья посуды',
  barcode: '40215987352',
  manufacturer: 'Нефис',
  brand:'AOS',
  price: '48,78',
},
{
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Items/promItems.js
> +            </div>
Это нужно выносить в отдельный компонент.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Items/promItems.js
> +            <div className="label">Популярное</div>
А зачем тут два мапинга массива items? Это должен быть один массив.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Items/promItems.js
> +              {item.name.split(' ').slice(1).join(' ')} {/* Остальные слова */}
Вот это обсуждали на занятии. Можно не делать первое слово жирным.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Items/promItems.js
> +          </div>
Вот ту нет переводов.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/MainLogo/MainLogo.tsx
> +        <Link className={styles.logo} href=""><Image src={Logo} alt=""></Image></Link>
```suggestion
        <Link className={styles.logo} href="">
            <Image src={Logo} alt=" />
        </Link>
```
У всех картинок должен быть alt.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/PhoneInfo/PhoneInfo.module.scss
> +            background-color: #1FD85D; // Зеленый цвет для индикатора
Не было исправлено.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/PhoneInfo/PhoneInfo.tsx
> +    )
```suggestion
    );
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Product categories/categories.js
> +          </div>
```suggestion
            <div className="itemC-name">
              <strong>{itemC.name}</strong> {/* Первое слово жирным */}
            </div>
          </div>
```

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Product categories/data.js
> +  id: 0, // Used in JSX as a key
Как ключ можно использовать imageId, а это удалить.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Slider/slider.jsx
> +    }, []);
Этот вопрос остался без ответа.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Sponsor/sponsor.tsx
> +                <span style={{ color: '#FFBF00' }}>ЛУЧШИЕ</span> ТОВАРЫ
Все стили задавать через классы.

2024-12-07 10:37 UTC, olya-yevsieienko commented on src/components/Sponsor/sponsor.tsx
> +            <div style={{ color: 'gray' }}>От ведущих мировых брендов</div>
Все стили задавать через классы.

2024-12-11 13:57 UTC, merged